server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://clonfer.dev.console.sco-qd.com:3306/clonf_dev?characterEncoding=utf-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: clonf
    password: XRYnIjl3
  redis:
    host: localhost
    port: 16379
    max-wait: 30000
    max-active: 1000
    max-idle: 20
    min-idle: 0
    timeout: 3000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtpout.secureserver.net
    username: contact@shiyirep.com
    password: Shiyi2021
    # 端口号465或587
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

minio:
  url: http://oss.hk.joellab.com:9000 # 服务地址
  access: clonfer # 账号
  secret: XRYnIjl3 # 密码
  bucket: clonfer # Bucket

security:
  jwt:
    secretKey: whatever

